language: node_js
node_js:
  - '20'

# Enable pull request builds
branches:
  only:
    - main
    - /^pull-request-.*$/

# Cache dependencies
cache:
  yarn: true
  directories:
    - node_modules

# Install dependencies
install:
  - yarn install --frozen-lockfile

# Run tests
script:
  - yarn test

# Environment variables
env:
  global:
    - SQUARE_ACCESS_TOKEN=$SQUARE_ACCESS_TOKEN
    - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    - CLERK_SECRET_KEY=$CLERK_SECRET_KEY

# Notifications
notifications:
  email:
    on_success: change
    on_failure: always
