language: node_js
node_js:
  - '20'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install --frozen-lockfile

script:
  - yarn test

env:
  global:
    - SQUARE_ACCESS_TOKEN=$SQUARE_ACCESS_TOKEN
    - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    - CLERK_SECRET_KEY=$CLERK_SECRET_KEY
